### ISSUE TITLE
OID Generation failed while trying to connect

### ISSUE THREAD

**Issue by nicof38** [nalbion/node-oracledb-for-lambda#2]
Hello,

I'm using your module in AWS Lamda, targeting nodejs 4.3 and I'm getting this error whatever Oracle database I'm targeting:

ORA-21561: OID generation failed

Our Oracle server is running 11g R2. 
Have you already got this error code while running this code in lambda ?

Note that running the code in an EC2 instance using the lambda development AMI is working fine

**Comment by vestgoteNL** [comment]
No answer for this still? I'm facing the same issue when trying to connect to remote oracle.

**Comment by nicof38** [comment]
Ok, here is the explanation: Oracle has a funny behavior where if the hostname given by hostname can't be resolved, it will fail connecting to the DB. Fortunately, in Linux, one can override the DNS entry for a session by writing an alias file in /tmp, then setting the environment variable HOSTALIASES to that file.

So adding this code to my function help to generate this file, and now I can successfully connect:

f = open('/tmp/HOSTALIASES','w')
str_host = os.uname()[1]
f.write(str_host + ' localhost\n')
f.close()

**Comment by martinthurn** [comment]
What language is the above snippet?  What exactly does os.uname() return?  (I need to do this in bash or Perl)  TIA

**Comment by nicof38** [comment]
This code is written in NodeJS (see first post). It helps to retrieve real hostname.
